<?php

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<div data-bind="scope: 'availableQty'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<!--<script type="text/javascript">-->
<!--    require(-->
<!--        ['Guentur_MageExperiments/component/module1', 'Training_Test/component/module2'],-->
<!--        (m1, m2) => {-->
<!---->
<!--        }-->
<!--    )-->
<!--</script>-->

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "availableQty": {
                    "component": "Guentur_MageExperiments/js/component/observable_timer",
                    "config": {
                        "template": "Guentur_MageExperiments/timer",
                        "rowResult": "<?= __('Available Qty: ') ?>",
                        "url": "<?= $escaper->escapeJs( $block->getUrl('training_front/index/availableQty')) ?>"
                    }
                }
            }
        }
    }
}
</script>
