<script type="text/javascript">
    requirejs(['Guentur_PulsestormJavascriptInitTutorial/simple-requirejs-module'], function(simpleRequirejsModule){
        alert("Loaded with simpleRequirejsModule dependency");
        console.log(simpleRequirejsModule);
    });

    requirejs(['Guentur_PulsestormJavascriptInitTutorial/example'], function(example){
        alert("Loaded with example dependency");
        console.log(example);
    });
</script>
